fix/Change ugettext_lazy to gettext_lazy
- Change from django.utils.translation import ugettext_lazy as _ to from django.utils.translation import gettext_lazy as _ to resolve issue ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'