Feature/146859/update to a modern version of django (#224)
* chore/Update django to v2.2

* feat/Add upgrade pip to Dockerfile.django

* chore/Update Django to v3.2

* chore/Update django-admin-sortable2 to v 1.0.4

* chore/Update django-cors-headers==2.3.0 to django-cors-headers==4.1.0

* refactor/Change simple-feedback to simple_feedback

- Add apps.py to mask simple-feedback to simple_feedback to avoid import issue.
- Remove redundant internal_ips.py.
- Change INSTALLED_APPS and urls.py to use the new settings.

This issue was caused by upgrading Dhango 2.x to 3.x since explicit validation for app labels was introduced.

* Merge dev into feature branch

* chore/Remove django-rest-auth==0.9.5 from requirements

* chore/Refactor authentication process

- Remove rest_auth and rest_auth.registration and switch to dj_rest_auth.
- Import SocialLoginView from dj_rest_auth instead of rest_auth.
- Import LoginSerializer instead of JWTSerializer (needs testing).
- Switch urls from rest-auth to dj-rest-auth.

* chore/Refactor NullBooleanField to BooleanField with allow_null=True

* chore/Refactor base_name to basename to conform with django upgrade

* chore/Remove custom mplementation for simple-feedback

- Remove app.py and custom umplementation for simple_feedback package.
- Upgrade django-redis==4.9.0 to django-redis==5.3.0.
- Upgrade redis==2.10.6 to redis==4.6.0.

* chore/Update packages to resolve dependency issues

- Update drf-yasg==1.17.1 to drf-yasg==1.21.6
- Update pytz==2018.5 to pytz==2023.3
- Update PyYAML==3.13 to PyYAML==6.0

* chore/Update JSONField import

- Change from django.contrib.postgres.fields import JSONField to from django.db.models import JSONField

* fix/Address error with CountryCustomQuestion and DonorCustomQuestion models

* Add DEFAULT_AUTO_FIELD to settings to suppress warnings

* chore/Update python docker image from python:3.7-stretch to python:3.8-slim-buster

* chore/Change python docker image from python:3.8-slim-buster to python:3.8-buster

* chore/Add installation of libpq-dev gcc in the dockerfile

* chore/Major changes in requirements.txt

- Add comments on updated packages
- Update celery to latest version 5.3.1
- Update billiard, kombu and vine to latest versions to support latest celery update

* chore/Update dockerfile to include upgrading of setuptools and wheel

* chore/Add dependencies to support upgrading ipython from 0.12.1 to 8.12.2

* chore/Update parso from 0.3.0 to 0.8.3 to resolve jedi dependency issues

* chore/Add openpyxl to requirements.txt to resolve issue with missing dependencies

* chore/Remove not used libraries

- Remove simplegeneric. This package is discontinued and incompatible with python 3.8
- Remove six. This package is incompatible with django>3
- Remove dj-anonymizer and dj-anonymizer[bulk]
- Remove anonymizer/user.py

* chore/(STABLE) Upgrade django-appconf==1.0.2 to django-appconf==1.0.5

- Upgrading django-appconf==1.0.2 to django-appconf==1.0.5 resolved the import six issue.

This is the first stable edition with the upgraded Django 3.2 version of the requirements.

* chore/Update all django related libraries

- Update django-extensions
- Update django-import-export
- Update django-modeltranslation
- Update django-rosetta

* chore/Refactor requirements.txt file

* chore/Update pytest and secondary packages in latest versions

* chore/Remove deprecated and not directly relevant libraries

- Remove appnope
- Update argh==0.26.2 to argh==0.28.1
- Remove atomicwrites
- Remove backcall
- Remove bcrypt
- Remove behave
- Remove docopt
- Remove Fabric3
- Remove itypes
- Remove Jinja2
- Remove watchdog

* chore/Update packages to resolve inconsistencies

- Update attrs==18.1.0 to attrs==23.1.0
- Reinstated coreapi. Required by rest_framework to resolve AssertionError: `coreapi` must be installed for schema support
- Update dj-inmemorystorage==1.4.1 to dj-inmemorystorage==2.1.0
- Update flake8==3.8.2 to flake8==6.0.0
- Update mccabe==0.6.1 to mccabe==0.7.0
- Update pycodestyle==2.6.0 to pycodestyle==2.10.0
- Update pyflakes==2.2.0 to pyflakes==3.0.1

Remove commented out code.

* chore/Update remaining packages

* revert packages to explore admin panel issue

* chore/Remove unnecessary startup scripts

* [MAJOR]Update Django==3.2 to Django==4.2.3

- Try to update Django 3.2 to the latest version 4.2.3
- Update django-admin-sortable2==1.0.4 to django-admin-sortable2==2.1.8 to see if this resolves the issue with the broken admin panel page

* fix/Change ugettext_lazy to gettext_lazy

- Change from django.utils.translation import ugettext_lazy as _ to from django.utils.translation import gettext_lazy as _ to resolve issue ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'

* fix/Change import for KeyTextTransform

- Change from django.contrib.postgres.fields.jsonb import KeyTextTransform to from django.db.models.fields.json import KeyTextTransform. In Django 3.1 and later versions, KeyTextTransform has been moved to django.db.models.fields.json

* fix/Change ugettext to gettext

- Replace from django.utils.translation import override, ugettext to from django.utils.translation import override, gettext as _

* fix/Remove import url from django.conf.urls

- Change from django.conf.urls import url to from django.urls import path.

The url() function was deprecated in Django 3.1 and removed in Django 4.0. Needs to replaced with path() or re_path().

* fix/Check issue with django-import-export-celery module

- django-import-export-celery is currently used from a forked version of the original library and causes some inconsistencies. Check if we can use the original django-import-export-celery module
- Update django-allauth==0.41.0 to current latest django-allauth==0.54.0.

* chore/Change djangorestframework-jwt into djangorestframework-simplejwt

* chore/Update PostgreSQL from 10.4 to 15.2 in docker-compose and Tiltfile

* chore/Fix warnings on translation on building process

* feat/Add new authorization process

- djangorestframework-jwt does not support Django 4.2.3 and was replaced with djangorestframework-simplejwt==5.2.2. For this a new custom authorization process CustomTokenObtainPairView needed to be defined.
- To retain the specific response we need to override the token serializer and create a custom reponse.

* chore/Add comments and minor refactor to CustomTokenObtainPairSerializer

* UI changes

* chore/Add comments to requirements.txt

* feat/Create custom admin site

* feat/Add custom AdminSite to remove certain features

- Remove nav_sidebar

* Deployment to test environment (#194)

* UI changes (#182)

* Updated breadcrumbs My Initiatives to Initiatives link to inventory list (#183)

* Bugfix/130138/admin export users fails (#184)

* added background export action for auth users table

* patching the export_resource_classes to the User model

* added comment

* chore/Remove unnecessary commands from startup_actions

* chore/Silence opentelemetry logs in dev

* chore/Remove unnecessary log statements

* Feature/160750/make end phases config (#186)

* add_checkbox_end_phase_update_current_stage

* dynamically get end phases and hide them in phases board

* remove cache structire

---------

Co-authored-by: ladeniva2 <122989825+ladeniva2@users.noreply.github.com>

* Count last phase always as end phase (#187)

* Bugfix/increase dev test coverage (#190)

* feat/Add new attribute completion_marks_an_initiative_as_inactive to test files

* chore/Add custom migration files

* chore/Add print statements to add_taxonomies

* chore/Refactor code

- Move add_taxonomies functionality to a new migration file
- Revert add taxonomies to the previous state

* fix/Minor fix to add_taxonomies.py

- Add check to return first if it finds more than one

* increase coverage version 2

* remove return from def fill_named_model -initial form

---------

Co-authored-by: gkalomalos <georgios.kalomalos@sword-group.com>

* Revert "Count last phase always as end phase"

This reverts commit 9d7e5a4f05f19c7209becfeb71ae845e7f4ac7a3.

* Revert "dynamically get end phases and hide them in phases board"

This reverts commit d5671dbe75c5422bd9424e96c85d60de2c821ce9.

* remove tests for discontinued and remove duplicate class (#193)

---------

Co-authored-by: ladeniva2 <122989825+ladeniva2@users.noreply.github.com>
Co-authored-by: mgaliatsatou <122973661+mgaliatsatou@users.noreply.github.com>
Co-authored-by: gkalomalos <georgios.kalomalos@sword-group.com>

* chore/Update requirements.txt

- Upgrade azure-monitor-opentelemetry==1.0.0b13 to azure-monitor-opentelemetry==1.0.0b15
- Add opentelemetry-instrumentation-django==0.40b0 to get additional database transaction information in application insights
- Freeze opentelemetry-semantic-conventions==0.40b0 and opentelemetry-sdk==1.19.0 to avoid package conflicts.

* feat/Upgrade the css on admin panel to resolve issues

- Remove skip link, logout form and theme toggle
- Add Log out link
- Fix theme toggle on login form

* fix/Change JSONWebTokenAuthentication to JWTAuthentication to avoid import error

* fix/Change get_token implementation to avoid null user_profile id

* feat/Update deploy version to 4.0.0

* feat/Add custom submit_line.html to avoid css issues in django input css

* fix/Various improvements to the css of the admin panel

- Add "Save and add another" button where missing
- Fix css on delete button
- Fix comment section location on platform sections

* chore/Add migration files

* fix/Change staticfiles to static in master-inline.html to comply with django4 requirements

* fix/Change formatting to avoid ormat string with unnamed arguments cannot be properly localized warning

* chore/Apply formatting

* chore/Refactor admin register process to comply with the custom_admin_site

* fix/Remove default comment section from the platform sections

* feat/Register NewsItem to the custom_admin_site

* fix/Remove autocomplete field for UserProfile in ApprovalStateAdmin

---------

Co-authored-by: ladeniva2 <122989825+ladeniva2@users.noreply.github.com>
Co-authored-by: Alexa-Laf <131444412+Alexa-Laf@users.noreply.github.com>
Co-authored-by: mgaliatsatou <122973661+mgaliatsatou@users.noreply.github.com>